name: ml-en-action
channels:
  - pytorch
  - conda-forge
  - fastai
dependencies:
  - arviz
  - fastai
  - fastai2
  - hvplot
  - importnb
  - jupyterlab
  - kaggle
  - matplotlib
  - nodejs
  - numba
  - pandas
  - pip
  - pre-commit
  - proplot
  - pyarrow
  - pymc3
  - pytest
  - python=3.8
  - scikit-learn
  - scipy
  - seaborn
  - skorch
  - statsmodels
  - watermark
  - xlrd
  - mlxtend
  - pip:
      - sktime
